$ErrorActionPreference = "Stop"

function Get-TaxiMobileWorkspaceLayout {
    $infraRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
    $workspaceRoot = (Resolve-Path (Join-Path $infraRoot "..")).Path
    $runtimeRoot = Join-Path $workspaceRoot ".tools\portable-postgis"

    if (-not $infraRoot.StartsWith($workspaceRoot + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
        throw "The infrastructure directory is not inside the TaxiMobile workspace."
    }

    return @{
        WorkspaceRoot = $workspaceRoot
        InfraRoot = $infraRoot
        BackendRoot = Join-Path $workspaceRoot "backend"
        RuntimeRoot = $runtimeRoot
        PostgreSqlRoot = Join-Path $runtimeRoot "pgsql"
        DataRoot = Join-Path $runtimeRoot "data"
        LogRoot = Join-Path $runtimeRoot "logs"
        EnvironmentFile = Join-Path $infraRoot ".env"
    }
}

function Import-TaxiMobileEnvironment {
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter()]
        [switch]$SetProcessEnvironment
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "The local environment file does not exist: $Path"
    }

    $values = @{}
    foreach ($rawLine in Get-Content -LiteralPath $Path) {
        $line = $rawLine.Trim()
        if (-not $line -or $line.StartsWith("#")) {
            continue
        }

        $parts = $line -split "=", 2
        if ($parts.Length -ne 2 -or -not $parts[0].Trim()) {
            throw "The local environment file contains a malformed assignment."
        }

        $name = $parts[0].Trim()
        if ($name -notmatch '^[A-Z][A-Z0-9_]*$') {
            throw "The local environment file contains an invalid variable name: $name"
        }

        $values[$name] = $parts[1]
        if ($SetProcessEnvironment) {
            [Environment]::SetEnvironmentVariable($name, $parts[1], "Process")
        }
    }

    return $values
}

function Get-RequiredLocalValue {
    param(
        [Parameter(Mandatory)]
        [hashtable]$Values,

        [Parameter(Mandatory)]
        [string]$Name
    )

    if (-not $Values.ContainsKey($Name) -or -not $Values[$Name]) {
        throw "The local environment file is missing $Name."
    }
    return [string]$Values[$Name]
}

function Assert-SafeDatabaseIdentifier {
    param(
        [Parameter(Mandatory)]
        [string]$Value,

        [Parameter(Mandatory)]
        [string]$Name
    )

    if ($Value -notmatch '^[A-Za-z_][A-Za-z0-9_]{0,62}$') {
        throw "$Name must be a PostgreSQL identifier containing at most 63 letters, digits, or underscores."
    }
}

function Assert-SafeLocalSecret {
    param(
        [Parameter(Mandatory)]
        [string]$Value,

        [Parameter(Mandatory)]
        [string]$Name
    )

    # new-local-env.ps1 deliberately generates this URL- and SQL-safe alphabet.
    if ($Value.Length -lt 24 -or $Value.Length -gt 172 -or $Value -notmatch '^[A-Za-z0-9_-]+$') {
        throw "$Name must be a 24+ character local secret generated by scripts/new-local-env.ps1."
    }
}

function Invoke-CheckedNativeCommand {
    param(
        [Parameter(Mandatory)]
        [string]$FilePath,

        [Parameter()]
        [string[]]$Arguments = @(),

        [Parameter()]
        [string]$FailureMessage = "A required command failed."
    )

    $commandOutput = & $FilePath @Arguments 2>&1
    $exitCode = $LASTEXITCODE
    foreach ($line in $commandOutput) {
        Write-Host $line
    }
    if ($exitCode -ne 0) {
        throw "$FailureMessage Exit code: $exitCode"
    }
}

function Get-LocalDatabaseUrl {
    param(
        [Parameter(Mandatory)]
        [string]$User,

        [Parameter(Mandatory)]
        [string]$Password,

        [Parameter(Mandatory)]
        [string]$Database,

        [Parameter(Mandatory)]
        [int]$Port
    )

    Assert-SafeDatabaseIdentifier -Value $User -Name "POSTGRES_USER"
    Assert-SafeDatabaseIdentifier -Value $Database -Name "POSTGRES_DB"
    Assert-SafeLocalSecret -Value $Password -Name "POSTGRES_PASSWORD"
    return "postgresql+asyncpg://${User}:${Password}@127.0.0.1:${Port}/${Database}"
}

function Test-PortablePostgresRunning {
    param(
        [Parameter(Mandatory)]
        [hashtable]$Layout
    )

    $pgCtl = Join-Path $Layout.PostgreSqlRoot "bin\pg_ctl.exe"
    if (-not (Test-Path -LiteralPath $pgCtl -PathType Leaf) -or
        -not (Test-Path -LiteralPath (Join-Path $Layout.DataRoot "PG_VERSION") -PathType Leaf)) {
        return $false
    }

    & $pgCtl status -D $Layout.DataRoot *> $null
    return $LASTEXITCODE -eq 0
}

function Start-PortablePostgres {
    param(
        [Parameter(Mandatory)]
        [hashtable]$Layout,

        [Parameter(Mandatory)]
        [int]$Port,

        [Parameter()]
        [ValidateRange(5, 120)]
        [int]$WaitSeconds = 30
    )

    if (Test-PortablePostgresRunning -Layout $Layout) {
        return $false
    }

    New-Item -ItemType Directory -Force -Path $Layout.LogRoot | Out-Null
    $postgres = Join-Path $Layout.PostgreSqlRoot "bin\postgres.exe"
    $pgIsReady = Join-Path $Layout.PostgreSqlRoot "bin\pg_isready.exe"
    $standardOutput = Join-Path $Layout.LogRoot "postgresql.stdout.log"
    $standardError = Join-Path $Layout.LogRoot "postgresql.stderr.log"
    $serverProcess = Start-Process -FilePath $postgres -ArgumentList @(
        "-D", $Layout.DataRoot, "-h", "127.0.0.1", "-p", [string]$Port
    ) -WindowStyle Hidden -RedirectStandardOutput $standardOutput -RedirectStandardError $standardError -PassThru

    $deadline = (Get-Date).AddSeconds($WaitSeconds)
    do {
        $serverProcess.Refresh()
        if ($serverProcess.HasExited) {
            throw "Portable PostgreSQL exited during startup. Inspect $standardError."
        }
        & $pgIsReady --host=127.0.0.1 --port=$Port --quiet
        if ($LASTEXITCODE -eq 0 -and (Test-PortablePostgresRunning -Layout $Layout)) {
            return $true
        }
        Start-Sleep -Milliseconds 250
    } while ((Get-Date) -lt $deadline)

    if (-not $serverProcess.HasExited) {
        Stop-Process -Id $serverProcess.Id
    }
    throw "Portable PostgreSQL did not become ready within $WaitSeconds seconds. Inspect $standardError."
}

function Stop-PortablePostgres {
    param(
        [Parameter(Mandatory)]
        [hashtable]$Layout
    )

    if (-not (Test-PortablePostgresRunning -Layout $Layout)) {
        return $false
    }

    $pgCtl = Join-Path $Layout.PostgreSqlRoot "bin\pg_ctl.exe"
    Invoke-CheckedNativeCommand -FilePath $pgCtl -Arguments @(
        "stop", "-D", $Layout.DataRoot, "-m", "fast", "-w", "-t", "30"
    ) -FailureMessage "Portable PostgreSQL did not stop cleanly."
    return $true
}
